title = "Naxdocs"
gitRepoUrl = "https://github.com/naxious/naxdocs"
changelog = true

gitSourceBranch = "main"

# Docusaurus settings
[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

organizationName = "Naxious"
projectName = "naxdocs"
url = "https://naxious.github.io"
baseUrl = "/naxdocs"
tagline = "Docs for Naxious' projects"

# Home Settings
[home]
enabled = true
includeReadme = false
bannerImage = "/Images/ND_Banner.png"

[navbar]
title = "Naxdocs"

[navbar.logo]
src = "/Images/ND_Logo.png"

[[home.features]]
title = "Springer"
description = "Spring animation library capable of animating numbers, Vector2s, and Vector3s"

[footer]
style = "dark"
copyright = "Copyright © 2025 Naxious. Built with Moonwave and Docusaurus"
