title = "Naxdocs"
gitRepoUrl = "https://github.com/naxious/naxdocs"

gitSourceBranch = "main"
changelog = true

# Docusaurus settings
[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

organizationName = "Naxious"
projectName = "naxdocs"
url = "https://naxious.github.io"
baseUrl = "/naxdocs"
tagline = "Making Roblox Development Easier"

# Home Settings
[home]
enabled = true
includeReadme = false
bannerImage = "https://raw.githubusercontent.com/Naxious/naxdocs/refs/heads/main/.moonwave/static/Images/Naxdocs_BG_NoWords.png"

[navbar]
title = "Naxdocs"

[navbar.logo]
src = "https://raw.githubusercontent.com/Naxious/naxdocs/refs/heads/main/.moonwave/static/Images/NaxdocsLogoSmall.png"

[[navbar.items]]
href = "https://discord.gg/xRFMPffDAU"
label = "Discord"
position = "right"

[[home.features]]
title = "Syscore"
description = "An easy to use module framework that lets you specify the loading order with priority, and allows for easy debugging"

[[home.features]]
title = "Springer"
description = "A Spring animation library capable of animating numbers, Vector2s, and Vector3s"

[[home.features]]
title = "Observer"
description = "An Observer class that allows you to easily create and manage events, decoupling your project"

[footer]
style = "dark"
copyright = "Copyright © 2025 Naxious. Built with Moonwave and Docusaurus"
