name: Update Reference Docs

on:
    repository_dispatch:
        types: [update-reference-docs]
    workflow_dispatch:

permissions:
    contents: write
    
jobs:
    update-reference-docs:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            submodules: true
            with:
            node-version: '22'

        - name: Install dependencies
          uses: ok-nick/setup-aftman@v0.4.2
          with:
            cache: true

        - run: npm i -g moonwave

        - name: publish to github pages
          run: moonwave build

        - name: Update reference docs
          run: git submodule update --remote --recursive

        - name: Commit and push changes
          uses: stefanzweifel/git-auto-commit-action@v5

        - name: Deploy to github pages
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: build
            branch: main
